<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="WDPA_Test" tests="3" failures="2" timestamp="17 Nov 2018 01:09:25 GMT" time="77.876" errors="0">
  <testcase name="SetEvironmentLevel" time="0.177" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="Pickup_LTLFreight" time="61.253" classname="WDPA_Application.WDPA_SmokeTest">
    <failure type="java.lang.AssertionError" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: &amp;apos;2.53.0&amp;apos;, revision: &amp;apos;35ae25b1534ae328c771e0856c93e187490ca824&amp;apos;, time: &amp;apos;2016-03-15 10:43:46&amp;apos;
System info: host: &amp;apos;WTC-5159473-l2&amp;apos;, ip: &amp;apos;172.18.205.81&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_191&amp;apos;
Driver info: driver.version: ChromeDriver">
      <![CDATA[java.lang.AssertionError: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'WTC-5159473-l2', ip: '172.18.205.81', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: driver.version: ChromeDriver
at WDPA_Application.WDPA_SmokeTest.Pickup_LTLFreight(WDPA_SmokeTest.java:115)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- Pickup_LTLFreight -->
  <testcase name="Pickup_LTLFreight_Anonymous" time="76.04" classname="WDPA_Application.WDPA_SmokeTest">
    <failure type="java.lang.AssertionError" message="The system has experienced an unexpected problem and is unable to complete your request.">
      <![CDATA[java.lang.AssertionError: The system has experienced an unexpected problem and is unable to complete your request.
at WDPA_Application.WDPA_SmokeTest.Pickup_LTLFreight_Anonymous(WDPA_SmokeTest.java:127)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- Pickup_LTLFreight_Anonymous -->
</testsuite> <!-- WDPA_Test -->
