<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="WIDM_Test" tests="7" failures="1" timestamp="06 Dec 2018 18:01:09 GMT" time="136.568" errors="0">
  <testcase name="SetEvironmentLevel" time="0.478" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="WIDM_Registration_ErrorMessages" time="67.675" classname="AgileApplications.WIDM"/>
  <testcase name="WIDM_RegistrationEFWS" time="87.183" classname="AgileApplications.WIDM"/>
  <testcase name="WIDM_ForgotUserID" time="104.529" classname="AgileApplications.WIDM"/>
  <testcase name="WIDM_Registration" time="111.03" classname="AgileApplications.WIDM"/>
  <testcase name="WIDM_ResetPasswordSecret" time="126.883" classname="AgileApplications.WIDM"/>
  <testcase name="ResetPasswordWIDM_Email" time="134.171" classname="AgileApplications.WIDM">
    <failure type="java.lang.AssertionError" message="User not working.">
      <![CDATA[java.lang.AssertionError: User not working.
at AgileApplications.WIDM.ResetPasswordWIDM_Email(WIDM.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- ResetPasswordWIDM_Email -->
</testsuite> <!-- WIDM_Test -->
