<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="5" name="Default test" tests="1" failures="1" timestamp="18 Nov 2018 05:59:05 GMT" time="28.966" errors="0">
  <testcase name="Pickup_Ground" time="28.442" classname="WDPA_Application.WDPA">
    <failure type="java.lang.AssertionError" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: &amp;apos;2.53.0&amp;apos;, revision: &amp;apos;35ae25b1534ae328c771e0856c93e187490ca824&amp;apos;, time: &amp;apos;2016-03-15 10:43:46&amp;apos;
System info: host: &amp;apos;WTC-5159473-l2&amp;apos;, ip: &amp;apos;172.27.142.145&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_191&amp;apos;
Driver info: driver.version: ChromeDriver">
      <![CDATA[java.lang.AssertionError: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'WTC-5159473-l2', ip: '172.27.142.145', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: driver.version: ChromeDriver
at org.testng.Assert.fail(Assert.java:96)
at WDPA_Application.WDPA.Pickup_Ground(WDPA.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Pickup_Ground -->
  <testcase name="Pickup_Express" time="0.0" classname="WDPA_Application.WDPA">
    <ignored/>
  </testcase> <!-- Pickup_Express -->
  <testcase name="Pickup_ExpressFright" time="0.0" classname="WDPA_Application.WDPA">
    <ignored/>
  </testcase> <!-- Pickup_ExpressFright -->
  <testcase name="Looping_LTL" time="0.0" classname="WDPA_Application.WDPA">
    <ignored/>
  </testcase> <!-- Looping_LTL -->
  <testcase name="Pickup_LTLFreight" time="0.0" classname="WDPA_Application.WDPA">
    <ignored/>
  </testcase> <!-- Pickup_LTLFreight -->
  <testcase name="Pickup_LTLFreight_Anonymous" time="0.0" classname="WDPA_Application.WDPA">
    <ignored/>
  </testcase> <!-- Pickup_LTLFreight_Anonymous -->
</testsuite> <!-- Default test -->
