<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="5" name="USRC_Test" tests="55" failures="51" timestamp="01 May 2019 18:26:56 GMT" time="41.639" errors="0">
  <testcase name="SetEvironmentLevel" time="0.068" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="Create_Users_With_Account" time="6.756" classname="USRC_Application.USRC_General"/>
  <testcase name="Create_Users_With_Account" time="10.752" classname="USRC_Application.USRC_General"/>
  <testcase name="Create_Users_With_Account" time="10.784" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="11.31" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="11.807" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="12.444" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="12.953" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="17.955" classname="USRC_Application.USRC_General"/>
  <testcase name="Create_Users_With_Account" time="18.109" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="18.583" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="12.275" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="8.746" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="9.129" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="9.03" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="8.992" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="8.796" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="8.736" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.307" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.653" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.608" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.561" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.508" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.546" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.549" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.48" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.492" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.422" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.208" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.147" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.13" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.176" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.189" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="0.43" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.618" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.632" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.637" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.565" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.665" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.665" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.652" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.606" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.663" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.231" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.171" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.153" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.201" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.182" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.087" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.113" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.131" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.211" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.102" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.101" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="Create_Users_With_Account" time="4.109" classname="USRC_Application.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_TAKEN&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;This user ID has already been chosen by someone else. Please choose another user ID.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_General.Create_Users_With_Account(USRC_General.java:235)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- Create_Users_With_Account -->
  <testcase name="CheckLogin" time="0.0" classname="USRC_Application.USRC_General">
    <ignored/>
  </testcase> <!-- CheckLogin -->
  <testcase name="CreateUsers_User_Data" time="0.0" classname="USRC_Application.USRC_General">
    <ignored/>
  </testcase> <!-- CreateUsers_User_Data -->
  <testcase name="CreateUsers_AddressDetails" time="0.0" classname="USRC_Application.USRC_General">
    <ignored/>
  </testcase> <!-- CreateUsers_AddressDetails -->
  <testcase name="CreateUsers" time="0.0" classname="USRC_Application.USRC_General">
    <ignored/>
  </testcase> <!-- CreateUsers -->
  <testcase name="UpdateUserContactInformation" time="0.0" classname="USRC_Application.USRC_General">
    <ignored/>
  </testcase> <!-- UpdateUserContactInformation -->
</testsuite> <!-- USRC_Test -->
