<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="Soap_Execution.WebServices" tests="1" failures="1" timestamp="11 Mar 2019 21:09:11 GMT" time="0.944" errors="0">
  <testcase name="WebServices_CreateMeterNumber" time="0.944" classname="Soap_Execution.WebServices">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;&lt;HighestSeverity&gt;SUCCESS&lt;/HighestSeverity&gt;&quot;
     but: was &quot;&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
   &lt;SOAP-ENV:Header/&gt;
   &lt;SOAP-ENV:Body&gt;
      &lt;SOAP-ENV:Fault&gt;
         &lt;faultcode&gt;SOAP-ENV:Server&lt;/faultcode&gt;
         &lt;faultstring xml:lang=&quot;en&quot;&gt;Internal system error. Please try again later.&lt;/faultstring&gt;
         &lt;detail&gt;
            &lt;cause&gt;UnrecoverableInternalError&lt;/cause&gt;
            &lt;code&gt;500&lt;/code&gt;
            &lt;desc&gt;Internal system error. Please try again later.&lt;/desc&gt;
         &lt;/detail&gt;
      &lt;/SOAP-ENV:Fault&gt;
   &lt;/SOAP-ENV:Body&gt;
&lt;/SOAP-ENV:Envelope&gt;&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<HighestSeverity>SUCCESS</HighestSeverity>"
     but: was "<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>SOAP-ENV:Server</faultcode>
         <faultstring xml:lang="en">Internal system error. Please try again later.</faultstring>
         <detail>
            <cause>UnrecoverableInternalError</cause>
            <code>500</code>
            <desc>Internal system error. Please try again later.</desc>
         </detail>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at Soap_Execution.WebServices.WebServices_CreateMeterNumber(WebServices.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- WebServices_CreateMeterNumber -->
</testsuite> <!-- Soap_Execution.WebServices -->
