<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="WTC-5159473-l2" name="AgileApplications.WFCL" tests="14" failures="4" timestamp="09 Nov 2018 03:19:02 GMT" time="788.592" errors="0">
  <testcase name="Reset_Password_Email" time="150.951" classname="AgileApplications.WFCL"/>
  <testcase name="UserRegistration" time="92.629" classname="AgileApplications.WFCL"/>
  <testcase name="AccountRegistration_WDPA" time="75.825" classname="AgileApplications.WFCL"/>
  <testcase name="Password_Reset_Secret" time="113.463" classname="AgileApplications.WFCL"/>
  <testcase name="CreditCardRegistrationEnroll" time="180.792" classname="AgileApplications.WFCL"/>
  <testcase name="Forgot_User_Email" time="62.807" classname="AgileApplications.WFCL"/>
  <testcase name="AccountRegistration_INET" time="37.344" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="Request Access from the Account Administrator">
      <![CDATA[java.lang.AssertionError: Request Access from the Account Administrator
at org.testng.Assert.fail(Assert.java:96)
at AgileApplications.WFCL.AccountRegistration_INET(WFCL.java:198)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AccountRegistration_INET -->
  <testcase name="AccountRegistration_Linkage" time="36.938" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="Request Access from the Account Administrator">
      <![CDATA[java.lang.AssertionError: Request Access from the Account Administrator
at org.testng.Assert.fail(Assert.java:96)
at AgileApplications.WFCL.AccountRegistration_Linkage(WFCL.java:303)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AccountRegistration_Linkage -->
  <testcase name="AccountRegistration_Linkage" time="36.326" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="Request Access from the Account Administrator">
      <![CDATA[java.lang.AssertionError: Request Access from the Account Administrator
at org.testng.Assert.fail(Assert.java:96)
at AgileApplications.WFCL.AccountRegistration_Linkage(WFCL.java:303)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AccountRegistration_Linkage -->
  <testcase name="AccountRegistration_Admin" time="1.517" classname="AgileApplications.WFCL">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at AgileApplications.WFCL.AccountRegistration_Admin(WFCL.java:183)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AccountRegistration_Admin -->
  <testcase name="AccountRegistration_GFBO" classname="AgileApplications.WFCL">
    <skipped/>
  </testcase> <!-- AccountRegistration_GFBO -->
  <testcase name="TNT_Vat_Validation" classname="AgileApplications.WFCL">
    <skipped/>
  </testcase> <!-- TNT_Vat_Validation -->
  <testcase name="WADM_Invitaiton" classname="AgileApplications.WFCL">
    <skipped/>
  </testcase> <!-- WADM_Invitaiton -->
  <testcase name="Address_Mismatch" classname="AgileApplications.WFCL">
    <skipped/>
  </testcase> <!-- Address_Mismatch -->
</testsuite> <!-- AgileApplications.WFCL -->
