<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="CXS_Support.USRC_FDM" tests="1" failures="1" timestamp="29 Jan 2019 18:44:28 GMT" time="1.292" errors="0">
  <testcase name="EndtoEndEnrollment_UserID" time="1.292" classname="CXS_Support.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;enrollmentOptionsList&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;34219729-f5d8-44aa-bbf3-5b95bc341ffd&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;SYSTEM.UNEXPECTED.ERROR&quot;,&quot;message&quot;:&quot;We are unable to process this request. Please try again later or contact FedEx Customer Service.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "enrollmentOptionsList"
     but: was "{"transactionId":"34219729-f5d8-44aa-bbf3-5b95bc341ffd","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"We are unable to process this request. Please try again later or contact FedEx Customer Service."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at CXS_Support.USRC_FDM.EndtoEndEnrollment_UserID(USRC_FDM.java:139)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment_UserID -->
</testsuite> <!-- CXS_Support.USRC_FDM -->
