<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="MFAC_Application.MFAC" tests="16" failures="8" timestamp="15 Jun 2019 20:56:07 GMT" time="151.436" errors="0">
  <testcase name="IssuePinExpiration" time="3.015" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdev-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdev-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.IssuePinExpiration(MFAC.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinExpiration -->
  <testcase name="IssuePinExpiration" time="6.184" classname="MFAC_Application.MFAC"/>
  <testcase name="AdditionalEnrollmentExpiration" time="8.799" classname="MFAC_Application.MFAC"/>
  <testcase name="IssuePinExpiration" time="7.884" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.IssuePinExpiration(MFAC.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinExpiration -->
  <testcase name="AdditionalEnrollmentExpiration" time="18.627" classname="MFAC_Application.MFAC"/>
  <testcase name="IssuePinExpiration" time="7.881" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.IssuePinExpiration(MFAC.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinExpiration -->
  <testcase name="IssuePinExpiration" time="6.941" classname="MFAC_Application.MFAC"/>
  <testcase name="AdditionalEnrollmentExpiration" time="7.742" classname="MFAC_Application.MFAC"/>
  <testcase name="AdditionalEnrollmentExpiration" time="8.799" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.AdditionalEnrollmentExpiration(MFAC.java:333)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AdditionalEnrollmentExpiration -->
  <testcase name="AdditionalEnrollmentExpiration" time="7.879" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdrt-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.AdditionalEnrollmentExpiration(MFAC.java:333)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AdditionalEnrollmentExpiration -->
  <testcase name="AdditionalEnrollmentExpiration" time="16.065" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdev-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdev-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.AdditionalEnrollmentExpiration(MFAC.java:333)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AdditionalEnrollmentExpiration -->
  <testcase name="AdditionalEnrollmentExpiration" time="16.063" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdev-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdev-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.AdditionalEnrollmentExpiration(MFAC.java:333)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AdditionalEnrollmentExpiration -->
  <testcase name="IssuePinExpiration" time="3.013" classname="MFAC_Application.MFAC"/>
  <testcase name="IssuePinExpiration" time="3.019" classname="MFAC_Application.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;mfacdev-cos-vip.test.cloUser_Info.fedex.comnull&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "mfacdev-cos-vip.test.cloUser_Info.fedex.comnull"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC_Application.MFAC.IssuePinExpiration(MFAC.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinExpiration -->
  <testcase name="IssuePinExpiration" time="7.703" classname="MFAC_Application.MFAC"/>
  <testcase name="AdditionalEnrollmentExpiration" time="21.822" classname="MFAC_Application.MFAC"/>
</testsuite> <!-- MFAC_Application.MFAC -->
