<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="WTC-5159473-l2" name="USRC_Application.USRC_TestData_Update" tests="20" failures="8" timestamp="07 Jun 2019 20:34:00 GMT" time="682.141" errors="0">
  <testcase name="CheckMigration" time="83.649" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="2.475" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="59.573" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="123.432" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="1.565" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="71.706" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="2.728" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="1.395" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="37.398" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="107.645" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="25.266" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="1.604" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="95.635" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="12.925" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckMigration" time="1.482" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="2.115" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="1.788" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckMigration(USRC_TestData_Update.java:228)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckMigration -->
  <testcase name="CheckMigration" time="49.760" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="Check_WCRV_Status" classname="USRC_Application.USRC_TestData_Update">
    <skipped/>
  </testcase> <!-- Check_WCRV_Status -->
  <testcase name="UpdateUser" classname="USRC_Application.USRC_TestData_Update">
    <skipped/>
  </testcase> <!-- UpdateUser -->
</testsuite> <!-- USRC_Application.USRC_TestData_Update -->
