<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="WDPA_Application.WDPA_SmokeTest" tests="5" failures="1" timestamp="10 Apr 2019 17:53:15 GMT" time="632.512" errors="0">
  <testcase name="Pickup_LTLFreight_Anonymous" time="42.021" classname="WDPA_Application.WDPA_SmokeTest"/>
  <testcase name="Pickup_LTLFreight" time="154.589" classname="WDPA_Application.WDPA_SmokeTest"/>
  <testcase name="Pickup_Ground" time="168.661" classname="WDPA_Application.WDPA_SmokeTest">
    <failure type="java.lang.AssertionError" message="The system has experienced an unexpected problem and is unable to complete your request. Please contact FedEx Customer Service to schedule your pickup.">
      <![CDATA[java.lang.AssertionError: The system has experienced an unexpected problem and is unable to complete your request. Please contact FedEx Customer Service to schedule your pickup.
at org.testng.Assert.fail(Assert.java:96)
at WDPA_Application.WDPA_SmokeTest.Pickup_Ground(WDPA_SmokeTest.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Pickup_Ground -->
  <testcase name="Pickup_ExpressFreight" time="135.910" classname="WDPA_Application.WDPA_SmokeTest"/>
  <testcase name="Pickup_Express" time="131.331" classname="WDPA_Application.WDPA_SmokeTest"/>
</testsuite> <!-- WDPA_Application.WDPA_SmokeTest -->
